#!/bin/sh

set -e

case "${1}" in
  prereqs)
    exit 0
    ;;
esac

if ! grep -q wp360-firstboot /proc/cmdline; then
  exit 0
fi

get_variables () {
  set +e # This function does not work as intended with -e
  local_device_setup "$ROOT" "root file system"
  set -e
  ROOT_PART_NAME="$(lsblk -no kname "$DEV")"

  ROOT_DEV_NAME="$(lsblk -no pkname "$DEV")"
  ROOT_DEV="/dev/$ROOT_DEV_NAME"

  ROOT_PART_NUM=$(cat "/sys/block/$ROOT_DEV_NAME/$ROOT_PART_NAME/partition")

  ROOT_DEV_SIZE=$(cat "/sys/block/$ROOT_DEV_NAME/size")
  TARGET_END="$((ROOT_DEV_SIZE - 1 - 8388608))"
  if [ "$TARGET_END" -gt 4294967295 ]; then
    TARGET_END=4294967295
  fi
}

do_resize () {
  if ! parted -m "$ROOT_DEV" u s resizepart "$ROOT_PART_NUM" "$TARGET_END"; then
    FAIL_REASON="Partition table resize of the root partition ($DEV) failed\n$FAIL_REASON"
    return 1
  fi

  wait_for_udev 10
  resize2fs -f -p "$DEV"
  RET="$?"
  if [ "$RET" -ne 0 ]; then
    FAIL_REASON="Root partition resize failed\n$FAIL_REASON"
  fi
  RECOVERY_PARTITION_START=$((TARGET_END + 1))


  fdisk "$ROOT_DEV" <<EEOF
n
p
4
$RECOVERY_PARTITION_START

w
EEOF
  RET="$?"
  if [ "$RET" -ne 0 ]; then
    FAIL_REASON="Recovery partition creation failed\n$FAIL_REASON"
  fi

  return "$RET"
}

fix_diskid () {
  mkdir -p /run/wp360-firstboot
  mount -o rw "$DEV" "${rootmnt?}/"
  mount -o rw "${DEV%%?}1" /run/wp360-firstboot/

  OLD_DISKID="$(dd if="$ROOT_DEV" bs=4 count=1 skip=110 status=none | od -An -tx4 | cut -c2-9)"
  DISKID="$(cut /sys/class/net/eth0/address -d: -f3-6 | tr -d :)"
  local d="$DISKID"
  echo ${d:6:2}${d:4:2}${d:2:2}${d:0:2} | xxd -r -p | dd of="$ROOT_DEV" bs=4 count=1 seek=110 status=none

  sed -i 's| wp360-firstboot||g' /run/wp360-firstboot/cmdline.txt
  sed -i "s/$OLD_DISKID/$DISKID/g" "${rootmnt?}/etc/fstab"
  sed -i "s/$OLD_DISKID/$DISKID/" /run/wp360-firstboot/cmdline.txt

  serial=$(grep Serial /proc/cpuinfo | sed -E 's/Serial\s+:\s+//')
  host="wp360-${serial:0:8}"
  echo "$host" > "${rootmnt?}/etc/hostname"
  sed -E -i "s/127.0.1.1\s+.+/127.0.1.1\t\t$host/" "${rootmnt?}/etc/hosts"

  umount /run/wp360-firstboot
  umount "${rootmnt?}/"
  rmdir /run/wp360-firstboot
}

. /scripts/functions
. /scripts/local

log_begin_msg "Resizing root filesystem...\n\nDepending on storage size and speed, this may take a while."

get_variables
if ! [ -b "${ROOT_DEV}5" ]; then
  do_resize
  fix_diskid
  log_end_msg
  reboot -f
else
  log_warning_msg "Resize skipped due to unexpected partition table"
fi

exit 0
