#!/bin/sh

set -e

case "${1}" in
  prereqs)
    exit 0
    ;;
esac

if ! grep -q wp360-firstboot /proc/cmdline; then
  exit 0
fi

get_variables () {
  set +e # This function does not work as intended with -e
  local_device_setup "$ROOT" "root file system"
  set -e
  ROOT_PART_NAME="$(lsblk -no kname "$DEV")"

  ROOT_DEV_NAME="$(lsblk -no pkname "$DEV")"
  ROOT_DEV="/dev/$ROOT_DEV_NAME"

  ROOT_PART_NUM=$(cat "/sys/block/$ROOT_DEV_NAME/$ROOT_PART_NAME/partition")

  ROOT_DEV_SIZE=$(cat "/sys/block/$ROOT_DEV_NAME/size")
  TARGET_END="$((ROOT_DEV_SIZE - 1 - 8388608))"
  if [ "$TARGET_END" -gt 4294967295 ]; then
    TARGET_END=4294967295
  fi
}

do_resize () {
  if ! parted -m "$ROOT_DEV" u s resizepart "$ROOT_PART_NUM" "$TARGET_END"; then
    FAIL_REASON="Partition table resize of the root partition ($DEV) failed\n$FAIL_REASON"
    return 1
  fi

  wait_for_udev 10
  resize2fs -f -p "$DEV"
  RET="$?"
  if [ "$RET" -ne 0 ]; then
    FAIL_REASON="Root partition resize failed\n$FAIL_REASON"
  fi
  RECOVERY_PARTITION_START=$((TARGET_END + 1))


  fdisk "$ROOT_DEV" <<EEOF
n
p
4
$RECOVERY_PARTITION_START

w
EEOF
  RET="$?"
  if [ "$RET" -ne 0 ]; then
    FAIL_REASON="Recovery partition creation failed\n$FAIL_REASON"
  fi

  return "$RET"
}

fix_diskid () {
  OLD_DISKID="$(dd if="$ROOT_DEV" bs=4 count=1 skip=110 status=none | od -An -tx4 | cut -c2-9)"
  DISKID="$(cut /sys/class/net/eth0/address -d: -f3-6 --output-delimiter=)"
  fdisk "$ROOT_DEV" <<EEOF
x
i
0x$DISKID
r
EEOF

  mkdir -p /run/wp360-firstboot
  mount -o remount,rw "$ROOT" "${rootmnt?}/"
  mount -o rw "$(resolve_device "$BOOT_PART_DEV")" /run/wp360-firstboot/

  sed -i 's| wp360-firstboot||g' /run/new_diskid/cmdline.txt
  sed -i "s/$OLD_DISKID/$DISKID/g" "${rootmnt?}/etc/fstab"
  sed -i "s/$OLD_DISKID/$DISKID/" /run/new_diskid/cmdline.txt 
  umount /run/new_diskid
  mount -o remount,ro "$ROOT" "${rootmnt?}/"
  rmdir /run/new_diskid
}

. /scripts/functions
. /scripts/local

log_begin_msg "Resizing root filesystem...\n\nDepending on storage size and speed, this may take a while."

get_variables
if ! [ -b "${ROOT_DEV}5" ]; then
  do_resize
  fix_diskid
else
  log_warning_msg "Resize skipped due to unexpected partition table"
fi
log_end_msg

exit 0
