#!/bin/bash

case $1 in
  configure)
    dpkg-trigger update-initramfs
    ;;
  triggered)
    if [[ -f "$2" ]]
    then
      crtime=$(stat -c '%W' "$2")
      mtime=$(stat -c '%Y' "$2")
      if [[ "$crtime" -ge "$mtime" ]]
      then
        cat >> "$2" <<- \EOF
[SysCom]
Linux.Devicefile.2=/dev/ttyWP360-2
Linux.Devicefile.3=/dev/ttyWP360-3
Linux.Devicefile.4=/dev/ttyWP360-4

[SysFile]
PlaceholderFilePath.1=/media/user,$DRIVES$
PlaceholderFilePath.1.Volatile=1
EOF
      fi
    fi
    ;;
esac
